<a href="https://colab.research.google.com/github/Avigail-Spira/CS-381/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

#####Problem 1
######find the distinct/unique common items between these two
arrays

In [1]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

print(np.intersect1d(a, b))

NameError: ignored

#####Problem 2
######Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality

In [9]:
array = np.arange(1,16).reshape(5,3)
print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


#####Problem 3
######Transform the 5x3 array shown above in Problem 2 into a unidimensional array

In [18]:
array2D = list(np.array(array).flatten())
print(array2D)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


#####Problem 4
######Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [19]:
array3D = np.array(array).T
print(array3D)

[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]


#####Problem 5
######Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

In [20]:
again2D = np.array(array3D).T
print(again2D)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


#####Problem 6
######Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [ ]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

for i in b:
  if i in a:
    np.delete(a, i)
print(a)

#####Problem 7
1. What is the maximum yearly NYC consumption of water in millions of gallons per day?
2. How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.
3. What is the mean and the standard deviation of the per capita daily water consumption?
4. What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [53]:
df = pd.read_csv("https://raw.githubusercontent.com/Avigail-Spira/CS-381/main/Module6_Data.csv")
print(df)

maxima = list(np.max(df, axis = 0))
print(f"The maximum yearly NYC consumption of water in mullions of gallons per day is ", maxima[2])


print("There are ", np.shape(df['Year']), " calender years.")

mean = df['Per Capita(Gallons per person per day)'].mean()
sd = df['Per Capita(Gallons per person per day)'].std()
print("The mean of the per capita daily water consumption is ", mean, " and the standard deviation is ", sd)


    Year  New York City Population  NYC Consumption(Million gallons per day)  \
0   1979                 7102100.0                                    1512.0   
1   1980                 7071639.0                                    1506.0   
2   1981                 7089241.0                                    1309.0   
3   1982                 7109105.0                                    1382.0   
4   1983                 7181224.0                                    1424.0   
5   1984                 7234514.0                                    1465.0   
6   1985                 7274054.0                                    1326.0   
7   1986                 7319246.0                                    1351.0   
8   1987                 7342476.0                                    1447.0   
9   1988                 7353719.0                                    1484.0   
10  1989                 7344175.0                                    1402.0   
11  1990                 7335650.0      